#JReleaser 1.26.0
#Fri Sep 04 14:32:49 UTC 2026
commitFullHash=149115e90a10c791d5206e76f0ca98730a1dfa4a
commitShortHash=149115e
deployMavenCentralAppDeploymentId=01899df0-046a-4854-a166-35f489c3dfd5
deployMavenCentralAppNamespace=io.brunoborges
javaVendor=Azul Systems, Inc.
javaVersion=21.0.12
javaVmVersion=21.0.12+8-LTS
milestoneName=v1.0.14
platform=linux-x86_64
platformReplaced=linux-x86_64
previousTagName=v1.0.13
projectName=JairoSVG
projectSnapshot=false
projectVersion=1.0.14
projectVersionMajor=1
projectVersionMinor=0
projectVersionNumber=1.0.14
projectVersionPatch=14
releaseBranch=main
releaseName=v1.0.14
tagName=v1.0.14
timestamp=2026-09-04T14\:25\:06.171998828Z
