#JReleaser 1.26.0
#Wed Sep 30 20:38:39 UTC 2026
commitFullHash=98f67fa52d00856dd0e05d8f5b05f7c1ab5e2557
commitShortHash=98f67fa
deployMavenCentralAppDeploymentId=0c33f6f0-6309-4761-9f6e-e400dca5e61d
deployMavenCentralAppNamespace=io.brunoborges
javaVendor=Azul Systems, Inc.
javaVersion=21.0.12
javaVmVersion=21.0.12+8-LTS
milestoneName=v1.0.15
platform=linux-x86_64
platformReplaced=linux-x86_64
previousTagName=v1.0.14
projectName=JairoSVG
projectSnapshot=false
projectVersion=1.0.15
projectVersionMajor=1
projectVersionMinor=0
projectVersionNumber=1.0.15
projectVersionPatch=15
releaseBranch=main
releaseName=v1.0.15
tagName=v1.0.15
timestamp=2026-09-30T20\:26\:52.657572004Z
