#JReleaser 1.24.0
#Tue Jun 16 20:32:54 UTC 2026
commitFullHash=422c66f22ffcb718c0ef809bcb90d1c8666abc61
commitShortHash=422c66f
javaVendor=Eclipse Adoptium
javaVersion=17.0.19
javaVmVersion=17.0.19+10
milestoneName=v1.0.13
platform=linux-x86_64
platformReplaced=linux-x86_64
projectName=JairoSVG
projectSnapshot=false
projectVersion=1.0.13
projectVersionMajor=1
projectVersionMinor=0
projectVersionNumber=1.0.13
projectVersionPatch=13
releaseBranch=copilot/fix-release-job-failure-another-one
releaseName=v1.0.13
tagName=v1.0.13
timestamp=2026-06-16T20\:32\:54.524952601Z
